### ISSUE TITLE
Publish JS unminified for eyeballing

### ISSUE THREAD

**Issue by jackric** [tranphuquy19/gs-duplicator#9]
Currently when installing using the README steps, the script shown to the user is like:
```
(()=>{var t=[(t,e)=>{"use strict";var n,r;Object.defineProperty(e,"__esModule",{value:!0}),e.saveGitlabToolSettings=e.saveGitlabToken=e.
....
```

I understand the motive to publish a minified script for download size, but it makes it difficult for a user to scan the script for any malicious intent. I propose it is better to publish plain and `prettier`ed code so that users can glance over the extension code to verify "it does what it says on the tin".

**Comment by tranphuquy19** [comment]
You were right, I released 2 user scripts in the ./dist folder and one of them has not been minified yet.

See: https://github.com/tranphuquy19/gs-duplicator/commit/045681ef781cc721e86a83b117d55887253be3f9
